import { ZenButton } from "components.slint";

export component SettingsView inherits VerticalLayout {
    in property <string> download_dir: "";
    in property <int> listen_port: 6967;
    callback change_download_dir();

    padding: 24px; // Zen spacing
    spacing: 20px;

    Text {
        text: "Application Settings";
        font-size: 16px;
        font-weight: 800;
        color: #c0caf5;
    }

    VerticalLayout {
        spacing: 10px;
        Text {
            text: "Download Save Location:";
            color: #565f89;
            font-size: 13px;
            font-weight: 600;
        }

        Rectangle {
            background: #1a1b26; // Inner void
            border-radius: 8px;
            border-width: 1px;
            border-color: #292e42;

            VerticalLayout {
                padding: 12px;
                Text {
                    text: download_dir;
                    color: #ffffff;
                    font-weight: 700;
                    wrap: word-wrap;
                }
            }
        }

        ZenButton {
            text: "📁 Change Directory";
            primary: false;
            clicked => {
                change_download_dir();
            }
        }
    }

    Rectangle {
        height: 1px;
        background: #292e42; // Splitter line
    }

    HorizontalLayout {
        alignment: space-between;
        Text {
            text: "Listening Network Port:";
            color: #565f89;
            font-size: 14px;
            font-weight: 600;
        }

        Text {
            text: listen_port;
            color: #7dcfff; // Neo-Cyan accent highlight
            font-weight: 800;
            font-size: 14px;
        }
    }
}
