import { Button } from "std-widgets.slint";

export component SettingsView inherits VerticalLayout {
    in property <string> download_dir: "";
    in property <int> listen_port: 6967;
    callback change_download_dir();

    padding: 16px;
    spacing: 16px;

    Text {
        text: "Application Settings";
        font-size: 16px;
        font-weight: 700;
        color: #f8fafc;
    }

    VerticalLayout {
        spacing: 8px;
        Text {
            text: "Download Save Location:";
            color: #94a3b8;
            font-size: 12px;
        }

        Rectangle {
            background: #0f172a;
            border-radius: 4px;
            border-width: 1px;
            border-color: #334155;

            VerticalLayout {
                padding: 10px;
                Text {
                    text: download_dir;
                    color: #e2e8f0;
                    font-weight: 700;
                    wrap: word-wrap;
                }
            }
        }

        Button {
            text: "📁 Change Directory";
            clicked => {
                change_download_dir();
            }
        }
    }

    Rectangle {
        height: 1px;
        background: #334155;
    }

    HorizontalLayout {
        alignment: space-between;
        Text {
            text: "Listening Network Port:";
            color: #94a3b8;
        }

        Text {
            text: listen_port;
            color: #f8fafc;
            font-weight: 700;
        }
    }
}
