import { ZenButton } from "components.slint";
import { Theme, AppData, Logic } from "globals.slint";

export component SettingsView inherits VerticalLayout {
    padding: 24px;
    spacing: 20px;
    
    Text {
        text: "Application Settings";
        font-size: 16px;
        font-weight: 800;
        color: Theme.text-primary;
    }
    
    VerticalLayout {
        spacing: 10px;
        Text {
            text: "Download Save Location:";
            color: Theme.text-secondary;
            font-size: 13px;
            font-weight: 600;
        }
        
        Rectangle {
            background: Theme.background;
            border-radius: 8px;
            border-width: 1px;
            border-color: Theme.surface-hover;
            
            VerticalLayout {
                padding: 12px;
                Text {
                    text: AppData.download_dir;
                    color: #ffffff;
                    font-weight: 700;
                    wrap: word-wrap;
                }
            }
        }
        
        ZenButton {
            text: "📁 Change Directory";
            primary: false;
            clicked => {
                Logic.change_download_dir();
            }
        }
    }
    
    Rectangle {
        height: 1px;
        background: Theme.surface-hover;
    }
    
    HorizontalLayout {
        alignment: space-between;
        Text {
            text: "Listening Network Port:";
            color: Theme.text-secondary;
            font-size: 14px;
            font-weight: 600;
        }
        Text {
            text: AppData.listen_port;
            color: Theme.secondary;
            font-weight: 800;
            font-size: 14px;
        }
    }
}
